# -*- coding: utf-8 -*-
"""phishing_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10bRwE3RwBHUCpNcBXERY2OclayTYzptL
"""

# Install libraries if needed
!pip install pandas numpy matplotlib seaborn scikit-learn tensorflow

# Import everything
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries loaded successfully!")

# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00327/Training%20Dataset.arff"

# We'll use a pre-converted CSV version instead
df = pd.read_csv("https://raw.githubusercontent.com/GregaVrbancic/Phishing-Dataset/master/dataset_full.csv")

print("Dataset loaded!")
print("Shape:", df.shape)  # rows x columns
df.head()                  # show first 5 rows

# Check the last column - that's usually our target (phishing or not)
print("Column names (last 10):")
print(df.columns.tolist()[-10:])

# Check the target column
print("\nTarget value counts:")
print(df.iloc[:, -1].value_counts())

# Check for missing values
print("\nMissing values:")
print(df.isnull().sum().sum())

# Visualize class distribution
sns.countplot(x=df['phishing'], palette='coolwarm')
plt.title('Phishing vs Legitimate Websites')
plt.xticks([0, 1], ['Legitimate', 'Phishing'])
plt.ylabel('Count')
plt.xlabel('Class')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Separate features (X) and label (y)
X = df.drop('phishing', axis=1)
y = df['phishing']

print("Features shape:", X.shape)
print("Label shape:", y.shape)

# 2. Split into train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nTraining set size:", X_train.shape)
print("Testing set size:", X_test.shape)

# 3. Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nData is ready for modeling!")

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# 1. Create the model
dt_model = DecisionTreeClassifier(random_state=42)
# 2. Train it
dt_model.fit(X_train, y_train)

# 3. Predict on test set
dt_predictions = dt_model.predict(X_test)

# 4. Evaluate
print("Decision Tree Results:")
print("Accuracy:", accuracy_score(y_test, dt_predictions))
print("\nClassification Report:")
print(classification_report(y_test, dt_predictions))

# Confusion Matrix
cm = confusion_matrix(y_test, dt_predictions)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Legitimate', 'Phishing'],
            yticklabels=['Legitimate', 'Phishing'])
plt.title('Decision Tree - Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

from sklearn.ensemble import RandomForestClassifier
import time

# 1. Create the model
rf_model = RandomForestClassifier(
    n_estimators=100,  # 100 trees
    random_state=42,
    n_jobs=-1          # use all CPU cores to speed up
)

# 2. Track training time
start = time.time()
rf_model.fit(X_train, y_train)
end = time.time()

# 3. Predict
rf_predictions = rf_model.predict(X_test)

# 4. Evaluate
print("Random Forest Results:")
print("Accuracy:", accuracy_score(y_test, rf_predictions))
print("Training time:", round(end - start, 2), "seconds")
print("\nClassification Report:")
print(classification_report(y_test, rf_predictions))

# Confusion Matrix
cm_rf = confusion_matrix(y_test, rf_predictions)
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Legitimate', 'Phishing'],
            yticklabels=['Legitimate', 'Phishing'])
plt.title('Random Forest - Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Feature Importance
importances = rf_model.feature_importances_
feature_names = X.columns
indices = np.argsort(importances)[::-1][:15]

plt.figure(figsize=(10, 6))
sns.barplot(x=importances[indices], y=feature_names[indices], palette='Greens_r')
plt.title('Random Forest - Top 15 Most Important Features')
plt.xlabel('Importance Score')
plt.show()

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Create the model
svm_model = LinearSVC(
    random_state=42,
    max_iter=2000  # enough iterations to converge
)

# 2. Track training time
start = time.time()
svm_model.fit(X_train_scaled, y_train)  # notice we use SCALED data
end = time.time()

# 3. Predict
svm_predictions = svm_model.predict(X_test_scaled)  # scaled test data too

# 4. Evaluate
print("SVM Results:")
print("Accuracy:", accuracy_score(y_test, svm_predictions))
print("Training time:", round(end - start, 2), "seconds")
print("\nClassification Report:")
print(classification_report(y_test, svm_predictions))

cm_svm = confusion_matrix(y_test, svm_predictions)
sns.heatmap(cm_svm, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Legitimate', 'Phishing'],
            yticklabels=['Legitimate', 'Phishing'])
plt.title('SVM - Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# 1. Build the network architecture
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# 2. Compile the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 3. Print architecture summary
model.summary()

# Early stopping - stops training if no improvement
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# Train the network
start = time.time()
history = model.fit(
    X_train_scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)
end = time.time()

print("\nTraining time:", round(end - start, 2), "seconds")

# 1. Evaluate on test set
nn_predictions_prob = model.predict(X_test_scaled)
nn_predictions = (nn_predictions_prob > 0.5).astype(int)

print("Neural Network Results:")
print("Accuracy:", accuracy_score(y_test, nn_predictions))
print("Training time:", round(end - start, 2), "seconds")
print("\nClassification Report:")
print(classification_report(y_test, nn_predictions))

# 2. Confusion Matrix
cm_nn = confusion_matrix(y_test, nn_predictions)
sns.heatmap(cm_nn, annot=True, fmt='d', cmap='Purples',
            xticklabels=['Legitimate', 'Phishing'],
            yticklabels=['Legitimate', 'Phishing'])
plt.title('Neural Network - Confusion Matrix')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Plot training vs validation accuracy over epochs
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title('Neural Network - Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Validation')
plt.title('Neural Network - Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

# Final comparison of all models
models = ['Decision Tree', 'Random Forest', 'SVM', 'Neural Network']
accuracies = [
    accuracy_score(y_test, dt_predictions),
    accuracy_score(y_test, rf_predictions),
    accuracy_score(y_test, svm_predictions),
    accuracy_score(y_test, nn_predictions)
]
recalls = [0.93, 0.96, 0.92, 0.94]  # phishing recall from reports
fn_counts = [413, 249, 496, 355]
training_times = [1, 13.9, 16.14, round(end - start, 2)]

# 1. Accuracy Comparison
plt.figure(figsize=(12, 10))

plt.subplot(2, 2, 1)
bars = plt.bar(models, accuracies, color=['#3498db','#2ecc71','#e74c3c','#9b59b6'])
plt.title('Accuracy Comparison')
plt.ylabel('Accuracy')
plt.ylim(0.88, 1.0)
for bar, acc in zip(bars, accuracies):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.001,
             f'{acc:.3f}', ha='center', fontsize=9)
plt.xticks(rotation=15)

# 2. Phishing Recall Comparison
plt.subplot(2, 2, 2)
bars2 = plt.bar(models, recalls, color=['#3498db','#2ecc71','#e74c3c','#9b59b6'])
plt.title('Phishing Recall Comparison')
plt.ylabel('Recall')
plt.ylim(0.88, 1.0)
for bar, rec in zip(bars2, recalls):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.001,
             f'{rec:.2f}', ha='center', fontsize=9)
plt.xticks(rotation=15)

# 3. False Negatives Comparison
plt.subplot(2, 2, 3)
bars3 = plt.bar(models, fn_counts, color=['#3498db','#2ecc71','#e74c3c','#9b59b6'])
plt.title('Missed Phishing Sites (FN) — Lower is Better')
plt.ylabel('False Negatives')
for bar, fn in zip(bars3, fn_counts):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 5,
             str(fn), ha='center', fontsize=9)
plt.xticks(rotation=15)

# 4. Training Time Comparison
plt.subplot(2, 2, 4)
bars4 = plt.bar(models, training_times, color=['#3498db','#2ecc71','#e74c3c','#9b59b6'])
plt.title('Training Time (seconds)')
plt.ylabel('Seconds')
for bar, t in zip(bars4, training_times):
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.3,
             f'{t}s', ha='center', fontsize=9)
plt.xticks(rotation=15)

plt.suptitle('Phishing Detection — Model Comparison',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()